name = "NinePiecePuzzle"
uuid = "9cc77ca6-2f53-4ccd-a066-2ff93b1becbb"
authors = ["Tobias Thomas <tobias.thomas@tu-darmstadt.de>"]
version = "0.1.0"

[deps]
LinkedLists = "70f5e60a-1556-5f34-a19e-a48b3e4aaee9"
